using DashPetApp.Services;
using System;
using System.Globalization;
using System.Windows.Forms;

namespace DashPetApp.Models
{
    /// <summary>
    /// This program file makes some alterations to the base DataClasses file generated by Linq To SQL.
    /// Generally it overrides the string method in the generated classes to reflect a "base" or default value to be displayed.
    /// This is useful especially for column headers.
    /// </summary>
    public partial class DataClassesDataContext
    {
        private MailDefinition _email = new MailDefinition();
        private void SubmitDatabaseChanges()
        {
            try
            {
                SubmitChanges();
            }
            catch (Exception e)
            {
                MessageBox.Show($"{e}");
            }
        } // Allows to submit changes using the DataClassesDataContext class.
    }
    public partial class Room
    {
        public override string ToString()
        {
            return room_name;
        }
    }
    public partial class Vet
    {
        public override string ToString()
        {
            return vet_name;
        }
    }
    public partial class Owner
    {
        public override string ToString()
        {
            return owner_name;
        }
    }
    public partial class Pet
    {
        public override string ToString()
        {
            return pet_name;
        }
    }
    public partial class AnimalSpecies
    {
        public override string ToString()
        {
            return animalspecies_name;
        }
    }
    public partial class AnimalClass
    {
        public override string ToString()
        {
            return animalclass_name;
        }
    }
    public partial class TimeSlot
    {
        public override string ToString()
        {
            return timeslot_time;
        }
    }
    public partial class Service
    {
        public override string ToString()
        {
            return $"{service_name} - {service_price}{NumberFormatInfo.CurrentInfo.CurrencySymbol}";
        }
    }
}
